# A simple MySQL container.
FROM mariadb:latest
MAINTAINER Angel Casado
RUN apt-get install -y python3-software-properties 
RUN apt-get install -y python3 python3-pymysql python3-openssl python3-dev python3-pip
EXPOSE 3306
