# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "SARTESTOGN"
  config.vm.boot_timeout = 600

  config.vm.network "forwarded_port", guest: 80, host: 8383

  #config.vm.network "public_network", ip: "192.168.1.213", bridge: "eth0"
  config.vm.network "public_network", ip: "192.168.1.213", bridge: "enp2s0"

  config.vm.synced_folder "./public", "/var/www/public"
  config.vm.synced_folder "./html",   "/var/www/html"
  config.vm.synced_folder "/nfs",   "/nfs"
 # Enable provisioning with Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "main.yml"
  end
end

